[tools]
go = "1.24rc2"
lefthook = "1.10.10"
markdownlint-cli2 = "0.17.2"
trivy = "0.59.0"

[tasks."desktop:vet"]
description = "Run go vet on all subprojects"
dir = "desktop"
run = "mise run vet"

[tasks."desktop:fmt"]
description = "Run go fmt on all subprojects"
dir = "desktop"
run = "mise run fmt"